apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ql97kswyy-python
  janus-idp.io/tekton: ql97kswyy-python
  backstage.io/kubernetes-id: ql97kswyy-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ql97kswyy-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
